const SidebarData = [
    // {
    //     label: "Menu",
    //     isMainMenu: true,
    // },
    {
        label: "Dashboard",
        icon: "mdi mdi-home-variant-outline",
        url: "/dashboard",
        issubMenubadge: true,
        // bgcolor: "bg-primary",
        badgeValue: ""
    },
    {
        label: "Doctors",
        icon: "mdi mdi-doctor",
        isHasArrow: true,
        url: "/adddoctor",
    },    
    {
        label: "My Component",
        icon: "mdi mdi-doctor",
        isHasArrow: true,
        url: "/my-component",
    },    
    {
        label: "My Data",
        icon: "mdi mdi-doctor",
        isHasArrow: true,
        url: "/my-data-view",
    },
    {
        label: "Doctor Schedules",
        icon: "mdi mdi-doctor",
        isHasArrow: true,
        url: "/viewschedule",
    },
    {
        label: "patients",
        icon: "mdi mdi-email-outline",
        subItem: [
            // { sublabel: "View All Patients", link: "/createpatient" },
            { sublabel: "View All Patients", link: "/view-all-patient" },
            // { sublabel: "Patients Case Studies", link: "/patient-list" },
            { sublabel: "Patients Case Studies", link: "/patient-view" },
            { sublabel: "Medical History", link: "/compose-email" },
            { sublabel: "Dental History", link: "/compose-email" },
            { sublabel: "Drug History", link: "/compose-email" },
            { sublabel: "Social History", link: "/compose-email" },
            { sublabel: "Exam & Diagnosis", link: "/compose-email" },
            { sublabel: "Treatment Plans", link: "/compose-email" },
        ],
    },
{
        label: "Patients Appointments",
        icon: "mdi mdi-doctor",
        isHasArrow: true,
        url: "/calendar",
    },
    // {
    //     label: "Prescription",
    //     icon: "mdi mdi-doctor",
    //     isHasArrow: true,
    //     url: "/view-prescription",
    // },    
    {
        label: "Prescription",
        icon: "mdi mdi-doctor",
        isHasArrow: true,
        url: "/view-list-prescription",
    },     
    {
        label: "Prescription View",
        icon: "mdi mdi-doctor",
        isHasArrow: true,
        url: "/view-prescription",
    },    
    // {
    //     label: "Prescription",
    //     icon: "mdi mdi-doctor",
    //     isHasArrow: true,
    //     url: "/create-prescription",
    // },
    {
        label: "Inventory",
        icon: "mdi mdi-doctor",
        isHasArrow: true,
        url: "/calendar",
    },
    {
        label: "Insurance Providers",
        icon: "mdi mdi-doctor",
        isHasArrow: true,
        url: "/calendar",
    },
    {
        label: "Dropdowns Settings",
        icon: "mdi mdi-account-circle-outline",
        subItem: [
            { sublabel: "Settings Intra Oral (Soft Tissues)", link: "/auth-login" },
            { sublabel: "Setting Extra Orals", link: "/auth-register" },
            { sublabel: "Settings Appointment Status", link: "/auth-recoverpw" },
            { sublabel: "Settings Category", link: "/auth-lock-screen" },
            { sublabel: "Settings Sub Categories", link: "/auth-lock-screen" },
            { sublabel: "Settings Items", link: "/auth-lock-screen" },
            { sublabel: "Settings Medical History", link: "/auth-lock-screen" },
            { sublabel: "Settings Social History", link: "/auth-lock-screen" },
            { sublabel: "Settings Drug History", link: "/auth-lock-screen" },
            { sublabel: "Settings Dental History", link: "/auth-lock-screen" },
            { sublabel: "Settings Procedure Category", link: "/auth-lock-screen" },
            { sublabel: "Settings Procedures", link: "/auth-lock-screen" },
            { sublabel: "Settings Medicine Types", link: "/auth-lock-screen" },
            { sublabel: "Settings Medicine", link: "/auth-lock-screen" },
            { sublabel: "Settings Diagnosis", link: "/auth-lock-screen" },
            { sublabel: "Insurance Providers", link: "/auth-lock-screen" },
        ],
    },
    {
        label: "Lab",
        icon: "ri-table-2",
        subItem: [
            { sublabel: "Lab", link: "/tables-basic" },
            { sublabel: "Lab Report", link: "/tables-listjs" },
        ],
    },
    {
        label: "Financial Activities",
        icon: "mdi mdi-format-page-break",
        subItem: [
            { sublabel: "Account Header", link: "/pages-starter" },
            { sublabel: "Invoice", link: "/pages-maintenance" },
            { sublabel: "Expense", link: "/pages-comingsoon" },
            { sublabel: "Report", link: "/pages-timeline" },
        ],
    },
    {
        label: "Settings",
        icon: "ri-eraser-fill",
        // issubMenubadge: true,
        // bgcolor: "bg-danger",
        // badgeValue: "",
        subItem: [
            { sublabel: "Role Management", link: "/form-elements" },
            { sublabel: "User Management", link: "/form-validation" },
            { sublabel: "Application Settings", link: "/form-advanced" },
            { sublabel: "General Settings", link: "/form-editor" },
        ],
    }, 
    // {
    //     label: "Components",
    //     isMainMenu: true,
    // },
    // {
    //     label: "UI Elements",
    //     icon: "mdi mdi-briefcase-variant-outline",
    //     subItem: [
    //         { sublabel: "Alerts", link: "/ui-alerts" },
    //         { sublabel: "Badge", link: "/ui-badge" },
    //         { sublabel: "Breadcrumb", link: "/ui-breadcrumb" },
    //         { sublabel: "Buttons", link: "/ui-buttons" },
    //         { sublabel: "Cards", link: "/ui-cards" },
    //         { sublabel: "Carousel", link: "/ui-carousel" },
    //         { sublabel: "Dropdowns", link: "/ui-dropdowns" },
    //         { sublabel: "Grid", link: "/ui-grid" },
    //         { sublabel: "Images", link: "/ui-images" },
    //         { sublabel: "Lightbox", link: "/ui-lightbox" },
    //         { sublabel: "Modals", link: "/ui-modals" },
    //         { sublabel: "Offcanvas", link: "/ui-offcanvas" },
    //         { sublabel: "Range Slider", link: "/ui-rangeslider" },
    //         { sublabel: "Session Timeout", link: "/ui-sessiontimeout" },
    //         { sublabel: "Pagination", link: "/ui-pagination" },
    //         { sublabel: "Progress Bars", link: "/ui-progressbars" },
    //         { sublabel: "Placeholders", link: "/ui-placeholders" },
    //         { sublabel: "Tabs & Accordions", link: "/ui-tabs-accordions" },
    //         { sublabel: "Typography", link: "/ui-typography" },
    //         { sublabel: "Toasts", link: "/ui-toasts" },
    //         { sublabel: "Video", link: "/ui-video" },
    //         { sublabel: "Popovers & Tooltips", link: "/ui-popovers" },
    //         { sublabel: "Rating", link: "/ui-rating" },
    //     ],
    // },
    // {
    //     label: "Forms",
    //     icon: "ri-eraser-fill",
    //     issubMenubadge: true,
    //     bgcolor: "bg-danger",
    //     badgeValue: "8",
    //     subItem: [
    //         { sublabel: "Form Elements", link: "/form-elements" },
    //         { sublabel: "Form Validation", link: "/form-validation" },
    //         { sublabel: "Form Advanced Plugins", link: "/form-advanced" },
    //         { sublabel: "Form Editor", link: "/form-editor" },
    //         { sublabel: "Form File Upload", link: "/form-uploads" },
    //         { sublabel: "Form Wizard", link: "/form-wizard" },
    //         { sublabel: "Form Mask", link: "/form-mask" },
    //     ],
    // },
    // {
    //     label: "Tables",
    //     icon: "ri-table-2",
    //     subItem: [
    //         { sublabel: "Basic Tables", link: "/tables-basic" },
    //         { sublabel: "List Js", link: "/tables-listjs" },
    //         { sublabel: "React Datatables", link: "/table-datatables" },
    //     ],
    // },
    // {
    //     label: "Charts",
    //     icon: "ri-bar-chart-line",
    //     subItem: [
    //         { sublabel: "Apex Charts", link: "/chart-apexcharts" },
    //         { sublabel: "Chartjs Charts", link: "/chart-chartjscharts" },
    //         { sublabel: "Re Charts", link: "/chart-floatcharts" },
    //         { sublabel: "Knob Charts", link: "/chart-jknobcharts" },
    //         { sublabel: "Sparkline Charts", link: "/chart-sparklinecharts" },
    //     ],
    // },
    // {
    //     label: "Icons",
    //     icon: "ri-brush-line",
    //     subItem: [
    //         { sublabel: "Box Icons", link: "/icon-boxicon" },
    //         { sublabel: "Material Design", link: "/icons-materialdesign" },
    //         { sublabel: "Dripicons", link: "/icon-dripicons" },
    //         { sublabel: "Font Awesome", link: "/icons-fontawesome" },
    //     ],
    // },
    // {
    //     label: "Maps",
    //     icon: "ri-map-pin-line",
    //     subItem: [
    //         { sublabel: "Google Maps", link: "/maps-google" },
    //         { sublabel: "Vector Maps", link: "/maps-vector" },
    //     ],
    // },
    // {
    //     label: "Multi Level",
    //     icon: "ri-share-line",
    //     subItem: [
    //         { sublabel: "Level 1.1", link: "/#" },
    //         {
    //             sublabel: "Level 1.2", link: "/#",
    //             subMenu: [
    //                 { title: "Level 2.1" },
    //                 { title: "Level 2.2" },
    //             ],
    //         },
    //     ],
    // },
]
export default SidebarData;